import { AgentSpec, AgentStatus, DriverSpec, EnvVarSpec, ProjectAgentAvailability, ProjectAgentHealth, RunSandboxCleanupPolicy, RunSource, RunStatus, WorkspaceSpec, type Project, type ProjectAgent } from '../gen/agentcompose/v2/agentcompose_pb.js';
import { projectClient, runClient } from './client';
import { listWorkspacePresets, type WorkspacePreset } from './config';

export type AgentWorkFiles = { source: 'empty' | 'file' | 'git'; workspaceId: string; workspaceName: string; workspaceType: string; summary: string; configJson: string };
export type AgentEnvItem = { name: string; value: string; secret: boolean };
export type AgentRunSummary = { text: string; runningSessionCount: number; runningLoaderRunCount: number };
export type AgentLatestRun = { runType: string; status: string; runId: string; title: string; at: string };
export type AgentDefinition = { id:string;name:string;description:string;enabled:boolean;provider:string;model:string;systemPrompt:string;runtimeImageId:string;driver:string;guestImage:string;workspaceId:string;envItems:AgentEnvItem[];configJson:string;capsetIds:string[];availability:string;availabilityClass:'green'|'amber'|'red';health:string;healthClass:'green'|'amber'|'red';workFiles:AgentWorkFiles;currentRun:AgentRunSummary;latestRun:AgentLatestRun|null;createdAt:string;updatedAt:string;deletedAt:string;projectId?:string };
export type AgentDefinitionInput = {name:string;description:string;enabled:boolean;provider:string;model:string;systemPrompt:string;runtimeImageId:string;driver:string;guestImage:string;workspaceId:string;envItems:AgentEnvItem[];configJson:string;capsetIds:string[]};

export async function listAgentDefinitions(query=''):Promise<AgentDefinition[]>{const projects=await listProjects();const result:AgentDefinition[]=[];for(const summary of projects){const response=await projectClient.getProject({project:{projectId:summary.projectId},includeSpec:true});const project=response.project;if(!project)continue;for(const agent of project.agents){const spec=project.spec?.agents.find((value)=>value.name===agent.agentName);const mapped=agentFromV2(project,agent,spec);if(!query||mapped.name.toLowerCase().includes(query.toLowerCase()))result.push(mapped)}}return result}
export async function createAgentDefinition(input:AgentDefinitionInput):Promise<AgentDefinition>{const normalized=requestFromInput(input);const existing=await findUIProject();const agents=[...(existing?.spec?.agents??[]),await specFromInput(normalized)];const response=await projectClient.applyProject({spec:{...(existing?.spec??{}),name:existing?.spec?.name||'ui-agents',agents}});const agent=response.project?.agents.find((value)=>value.agentName===normalized.name);if(!response.project||!agent)throw new Error('智能体保存失败');return agentFromV2(response.project,agent,response.project.spec?.agents.find((value)=>value.name===agent.agentName))}
export async function updateAgentDefinition(id:string,input:AgentDefinitionInput):Promise<AgentDefinition>{const found=await findAgent(id);if(!found)throw new Error('智能体不存在');const normalized=requestFromInput(input);const nextSpec=await specFromInput(normalized);const agents=(found.project.spec?.agents??[]).map((value)=>value.name===found.agent.agentName?nextSpec:value);const response=await projectClient.applyProject({spec:{...found.project.spec!,agents}});const agent=response.project?.agents.find((value)=>value.agentName===normalized.name);if(!response.project||!agent)throw new Error('智能体保存失败');return agentFromV2(response.project,agent,response.project.spec?.agents.find((value)=>value.name===agent.agentName))}
export async function deleteAgentDefinition(id:string):Promise<void>{const found=await findAgent(id);if(!found)return;const agents=(found.project.spec?.agents??[]).filter((value)=>value.name!==found.agent.agentName);await projectClient.applyProject({spec:{...found.project.spec!,agents}})}
export async function runAgentDefinition(input:{agentId:string;driver:string;message:string}):Promise<{runId:string;sandboxId:string}>{const found=await findAgent(input.agentId);if(!found)throw new Error('智能体不存在');const response=await runClient.runAgent({projectId:found.project.summary?.projectId??'',agentName:found.agent.agentName,prompt:input.message,source:RunSource.MANUAL,driver:input.driver,cleanupPolicy:RunSandboxCleanupPolicy.KEEP_RUNNING});return{runId:response.run?.summary?.runId??'',sandboxId:response.run?.summary?.sandboxId??''}}

async function listProjects(){const result=[];let offset=0;for(;;){const response=await projectClient.listProjects({limit:200,offset});result.push(...response.projects);if(!response.hasMore)break;offset=response.nextOffset}return result}
async function findUIProject():Promise<Project|undefined>{for(const summary of await listProjects()){if(summary.name==='ui-agents'){return (await projectClient.getProject({project:{projectId:summary.projectId},includeSpec:true})).project}}return undefined}
async function findAgent(id:string):Promise<{project:Project;agent:ProjectAgent}|undefined>{const target=parseAgentFallbackId(id);for(const summary of await listProjects()){const project=(await projectClient.getProject({project:{projectId:summary.projectId},includeSpec:true})).project;if(!project)continue;if(target&&project.summary?.projectId!==target.projectId)continue;const agent=target?project.agents.find((value)=>value.agentName===target.agentName):project.agents.find((value)=>(Boolean(id)&&value.managedAgentId===id)||value.agentName===id);if(agent)return{project,agent}}return undefined}
function requestFromInput(input:AgentDefinitionInput):AgentDefinitionInput{return{...input,name:input.name.trim(),provider:normalizeAgentProvider(input.provider),model:input.model.trim(),systemPrompt:input.systemPrompt.trim(),driver:input.driver.trim(),guestImage:input.guestImage.trim(),workspaceId:input.workspaceId.trim(),envItems:input.envItems.map((v)=>({...v,name:v.name.trim()})).filter((v)=>v.name),capsetIds:input.capsetIds.map((v)=>v.trim()).filter(Boolean)}}
async function specFromInput(input:AgentDefinitionInput):Promise<AgentSpec>{return new AgentSpec({name:input.name,provider:input.provider,model:input.model,systemPrompt:input.systemPrompt,image:input.guestImage,driver:input.driver?new DriverSpec({name:input.driver}):undefined,env:input.envItems.map((value)=>new EnvVarSpec(value)),workspace:await workspaceSpecFromInput(input),capsetIds:input.capsetIds,status:input.enabled?AgentStatus.ENABLED:AgentStatus.DISABLED})}
async function workspaceSpecFromInput(input:AgentDefinitionInput):Promise<WorkspaceSpec|undefined>{if(!input.workspaceId)return undefined;const preset=(await listWorkspacePresets()).find((value)=>value.id===input.workspaceId);if(!preset)throw new Error('Workspace 配置不存在');return workspaceSpecFromPreset(preset)}
function workspaceSpecFromPreset(preset:WorkspacePreset):WorkspaceSpec{const config=jsonObject(preset.configJson);if(preset.type==='git')return new WorkspaceSpec({name:preset.id,provider:'git',url:stringValue(config.url)||stringValue(config.repo_url)||stringValue(config.repoUrl),branch:stringValue(config.branch),path:stringValue(config.path)||'.'});return new WorkspaceSpec({name:preset.id,provider:'local',path:stringValue(config.path)||preset.id})}
function jsonObject(value:string):Record<string,unknown>{try{const parsed=JSON.parse(value||'{}');return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed as Record<string,unknown>:{}}catch{return{}}}
function stringValue(value:unknown):string{return typeof value==='string'?value.trim():''}
function normalizeAgentProvider(value:string):string{const provider=value.trim().toLowerCase();if(['claude','gemini','codex','opencode'].includes(provider))return provider;throw new Error(`不支持的智能体 Provider：${value||'-'}`)}
function agentFromV2(project:Project,item:ProjectAgent,spec?:AgentSpec):AgentDefinition{const enabled=spec?spec.status!==AgentStatus.DISABLED:item.enabled;const workspaceId=spec?.workspace?.name??'';const projectId=project.summary?.projectId??'';const completeSpecProjection=Boolean(spec&&item.managedAgentId.trim()&&item.agentName.trim()&&item.provider.trim());const canonicalSpecMisread=completeSpecProjection&&item.availability===ProjectAgentAvailability.VALIDATION_FAILED;const availability=canonicalSpecMisread?(enabled?ProjectAgentAvailability.AVAILABLE:ProjectAgentAvailability.UNAVAILABLE):(enabled?item.availability:ProjectAgentAvailability.UNAVAILABLE);const health=canonicalSpecMisread&&item.latestRun?.status!==RunStatus.FAILED?ProjectAgentHealth.HEALTHY:item.health;return{id:agentIdFromV2(projectId,item),name:item.agentName,description:'',enabled,provider:item.provider||'codex',model:item.model,systemPrompt:spec?.systemPrompt??'',runtimeImageId:'',driver:item.driver,guestImage:item.image,workspaceId,envItems:(spec?.env??[]).map((v)=>({name:v.name,value:v.value,secret:v.secret})),configJson:'{}',capsetIds:spec?.capsetIds??[],availability:availability===ProjectAgentAvailability.AVAILABLE?'可用':availability===ProjectAgentAvailability.UNAVAILABLE?'不可用':availability===ProjectAgentAvailability.VALIDATION_FAILED?'校验失败':'未知',availabilityClass:availability===ProjectAgentAvailability.AVAILABLE?'green':availability===ProjectAgentAvailability.UNAVAILABLE?'amber':'red',health:health===ProjectAgentHealth.HEALTHY?'健康':health===ProjectAgentHealth.AT_RISK?'有风险':'未知',healthClass:health===ProjectAgentHealth.HEALTHY?'green':health===ProjectAgentHealth.AT_RISK?'amber':'red',workFiles:{source:spec?.workspace?.provider==='git'?'git':spec?.workspace?'file':'empty',workspaceId,workspaceName:spec?.workspace?.name??'',workspaceType:spec?.workspace?.provider??'',summary:spec?.workspace?.path??'',configJson:''},currentRun:{text:item.currentRun?.text??'暂无运行',runningSessionCount:item.currentRun?.runningRunCount??0,runningLoaderRunCount:item.currentRun?.runningSchedulerRunCount??0},latestRun:item.latestRun?{runType:item.latestRun.source===RunSource.SCHEDULER?'scheduler':'manual',status:RunStatus[item.latestRun.status]??'',runId:item.latestRun.runId,title:'',at:timestampString(item.latestRun.at)}:null,createdAt:'',updatedAt:'',deletedAt:'',projectId}}
function agentIdFromV2(projectId:string,item:ProjectAgent):string{return item.managedAgentId.trim()||`project:${encodeURIComponent(projectId)}:agent:${encodeURIComponent(item.agentName)}`}
function parseAgentFallbackId(id:string):{projectId:string;agentName:string}|undefined{const match=/^project:([^:]+):agent:(.+)$/.exec(id);return match?{projectId:decodeURIComponent(match[1]),agentName:decodeURIComponent(match[2])}:undefined}
function timestampString(value?:{seconds:bigint;nanos:number}){return value?new Date(Number(value.seconds)*1000+value.nanos/1e6).toISOString():''}
