import { AgentStatus, ProjectAgentAvailability, ProjectAgentHealth, RunSource, RunStatus, type AgentSpec, type Project, type ProjectAgent } from '../gen/agentcompose/v2/agentcompose_pb.js';
import { projectClient, runClient } from './client';

export type AgentWorkFiles = { source: 'empty' | 'file' | 'git'; workspaceId: string; workspaceName: string; workspaceType: string; summary: string; configJson: string };
export type AgentEnvItem = { name: string; value: string; secret: boolean };
export type AgentRunSummary = { text: string; runningSessionCount: number; runningLoaderRunCount: number };
export type AgentLatestRun = { runType: string; status: string; runId: string; title: string; at: string };
export type AgentDefinition = { id:string;name:string;description:string;enabled:boolean;provider:string;model:string;systemPrompt:string;runtimeImageId:string;driver:string;guestImage:string;workspaceId:string;envItems:AgentEnvItem[];configJson:string;capsetIds:string[];availability:string;availabilityClass:'green'|'amber'|'red';health:string;healthClass:'green'|'amber'|'red';workFiles:AgentWorkFiles;currentRun:AgentRunSummary;latestRun:AgentLatestRun|null;createdAt:string;updatedAt:string;deletedAt:string;projectId?:string };
export type AgentDefinitionInput = {name:string;description:string;enabled:boolean;provider:string;model:string;systemPrompt:string;runtimeImageId:string;driver:string;guestImage:string;workspaceId:string;envItems:AgentEnvItem[];configJson:string;capsetIds:string[]};

export async function listAgentDefinitions(query=''):Promise<AgentDefinition[]>{const projects=await listProjects();const result:AgentDefinition[]=[];for(const summary of projects){const response=await projectClient.getProject({project:{projectId:summary.projectId},includeSpec:true});const project=response.project;if(!project)continue;for(const agent of project.agents){const spec=project.spec?.agents.find((value)=>value.name===agent.agentName);const mapped=agentFromV2(project,agent,spec);if(!query||mapped.name.toLowerCase().includes(query.toLowerCase()))result.push(mapped)}}return result}
export async function createAgentDefinition(input:AgentDefinitionInput):Promise<AgentDefinition>{const normalized=requestFromInput(input);const existing=await findUIProject();const agents=[...(existing?.spec?.agents??[]),specFromInput(normalized)];const response=await projectClient.applyProject({spec:{...(existing?.spec??{}),name:existing?.spec?.name||'ui-agents',agents},expectedSpecHash:existing?.summary?.specHash??''});const agent=response.project?.agents.find((value)=>value.agentName===normalized.name);if(!response.project||!agent)throw new Error('智能体保存失败');return agentFromV2(response.project,agent,response.project.spec?.agents.find((value)=>value.name===agent.agentName))}
export async function updateAgentDefinition(id:string,input:AgentDefinitionInput):Promise<AgentDefinition>{const found=await findAgent(id);if(!found)throw new Error('智能体不存在');const normalized=requestFromInput(input);const agents=(found.project.spec?.agents??[]).map((value)=>value.name===found.agent.agentName?specFromInput(normalized):value);const response=await projectClient.applyProject({spec:{...found.project.spec!,agents},expectedSpecHash:found.project.summary?.specHash??''});const agent=response.project?.agents.find((value)=>value.agentName===normalized.name);if(!response.project||!agent)throw new Error('智能体保存失败');return agentFromV2(response.project,agent,response.project.spec?.agents.find((value)=>value.name===agent.agentName))}
export async function deleteAgentDefinition(id:string):Promise<void>{const found=await findAgent(id);if(!found)return;const agents=(found.project.spec?.agents??[]).filter((value)=>value.name!==found.agent.agentName);await projectClient.applyProject({spec:{...found.project.spec!,agents},expectedSpecHash:found.project.summary?.specHash??''})}
export async function createAgentDefinitionSession(input:{agentId:string;title:string;workspaceId:string;driver:string;guestImage:string;message:string;provider:string}):Promise<string>{const found=await findAgent(input.agentId);if(!found)throw new Error('智能体不存在');const response=await runClient.runAgent({projectId:found.project.summary?.projectId??'',agentName:found.agent.agentName,prompt:input.message,source:RunSource.MANUAL,driver:input.driver});return response.run?.summary?.sandboxId??''}

async function listProjects(){const result=[];let offset=0;for(;;){const response=await projectClient.listProjects({limit:200,offset});result.push(...response.projects);if(!response.hasMore)break;offset=response.nextOffset}return result}
async function findUIProject():Promise<Project|undefined>{for(const summary of await listProjects()){if(summary.name==='ui-agents'){return (await projectClient.getProject({project:{projectId:summary.projectId},includeSpec:true})).project}}return undefined}
async function findAgent(id:string):Promise<{project:Project;agent:ProjectAgent}|undefined>{for(const summary of await listProjects()){const project=(await projectClient.getProject({project:{projectId:summary.projectId},includeSpec:true})).project;if(!project)continue;const agent=project.agents.find((value)=>value.managedAgentId===id||value.agentName===id);if(agent)return{project,agent}}return undefined}
function requestFromInput(input:AgentDefinitionInput):AgentDefinitionInput{return{...input,name:input.name.trim(),provider:normalizeAgentProvider(input.provider),model:input.model.trim(),systemPrompt:input.systemPrompt.trim(),driver:input.driver.trim(),guestImage:input.guestImage.trim(),workspaceId:input.workspaceId.trim(),envItems:input.envItems.map((v)=>({...v,name:v.name.trim()})).filter((v)=>v.name),capsetIds:input.capsetIds.map((v)=>v.trim()).filter(Boolean)}}
function specFromInput(input:AgentDefinitionInput):AgentSpec{return{name:input.name,provider:input.provider,model:input.model,systemPrompt:input.systemPrompt,image:input.guestImage,driver:input.driver?{name:input.driver}:undefined,env:input.envItems,capsetIds:input.capsetIds,status:input.enabled?AgentStatus.ENABLED:AgentStatus.DISABLED}}
function normalizeAgentProvider(value:string):string{const provider=value.trim().toLowerCase();if(['claude','gemini','codex','opencode'].includes(provider))return provider;throw new Error(`不支持的智能体 Provider：${value||'-'}`)}
function agentFromV2(project:Project,item:ProjectAgent,spec?:AgentSpec):AgentDefinition{const availability=item.availability;const health=item.health;return{id:item.managedAgentId,name:item.agentName,description:'',enabled:item.enabled,provider:item.provider||'codex',model:item.model,systemPrompt:spec?.systemPrompt??'',runtimeImageId:'',driver:item.driver,guestImage:item.image,workspaceId:'',envItems:(spec?.env??[]).map((v)=>({name:v.name,value:v.value,secret:v.secret})),configJson:'{}',capsetIds:spec?.capsetIds??[],availability:availability===ProjectAgentAvailability.AVAILABLE?'可用':availability===ProjectAgentAvailability.UNAVAILABLE?'不可用':availability===ProjectAgentAvailability.VALIDATION_FAILED?'校验失败':'未知',availabilityClass:availability===ProjectAgentAvailability.AVAILABLE?'green':availability===ProjectAgentAvailability.UNAVAILABLE?'amber':'red',health:health===ProjectAgentHealth.HEALTHY?'健康':health===ProjectAgentHealth.AT_RISK?'有风险':'未知',healthClass:health===ProjectAgentHealth.HEALTHY?'green':health===ProjectAgentHealth.AT_RISK?'amber':'red',workFiles:{source:spec?.workspace?.provider==='git'?'git':spec?.workspace?'file':'empty',workspaceId:'',workspaceName:spec?.workspace?.name??'',workspaceType:spec?.workspace?.provider??'',summary:spec?.workspace?.path??'',configJson:''},currentRun:{text:item.currentRun?.text??'暂无运行',runningSessionCount:item.currentRun?.runningRunCount??0,runningLoaderRunCount:item.currentRun?.runningSchedulerRunCount??0},latestRun:item.latestRun?{runType:item.latestRun.source===RunSource.SCHEDULER?'scheduler':'manual',status:RunStatus[item.latestRun.status]??'',runId:item.latestRun.runId,title:'',at:timestampString(item.latestRun.at)}:null,createdAt:'',updatedAt:'',deletedAt:'',projectId:project.summary?.projectId}}
function timestampString(value?:{seconds:bigint;nanos:number}){return value?new Date(Number(value.seconds)*1000+value.nanos/1e6).toISOString():''}
