import { RunAgentStreamEventType, RunEventKind, RunSource, type Sandbox } from '../gen/agentcompose/v2/agentcompose_pb.js';
import { runClient, sandboxClient } from './client';

export enum CellType { UNSPECIFIED=0, SHELL=1, JAVASCRIPT=2, PYTHON=3, AGENT=4 }
export type WorkSession={id:string;title:string;status:string;driver:string;guestImage:string;workspacePath:string;triggerSource:string;createdAt:string;updatedAt:string;cellCount:number;eventCount:number;tags:Array<{name:string;value:string}>};
export type WorkSessionDetail=WorkSession&{proxyPath:string;notebookUrl:string};
export type WorkSessionCell={id:string;source:string;output:string;type:CellType;exitCode:number;success:boolean;createdAt:string;agent:string;agentSessionId:string;stopReason:string;running:boolean};
export type WorkSessionEvent={id:string;type:string;level:string;message:string;createdAt:string};
export type WorkSessionWatchEvent={type:'session';session:WorkSession}|{type:'event';event:WorkSessionEvent}|{type:'cell';cell:WorkSessionCell}|{type:'chunk';cellId:string;chunk:string;isStderr:boolean};
export type WorkSessionRunTarget={projectId:string;agentName:string};

export async function listWorkSessions(limit=50,offset=0):Promise<{sessions:WorkSession[];hasMore:boolean;totalCount:number}>{let token='';let skipped=0;const sessions:WorkSession[]=[];for(;;){const response=await sandboxClient.listSandboxes({limit:Math.min(500,limit+offset),pageToken:token});for(const item of response.sandboxes){if(skipped++<offset)continue;if(sessions.length<limit)sessions.push(sessionFromSandbox(item))}token=response.nextPageToken;if(!token||sessions.length>=limit)return{sessions,hasMore:Boolean(token)||response.sandboxes.length>sessions.length,totalCount:offset+sessions.length+(token?1:0)}}}
export async function getWorkSession(id:string,_options:{includeProxy?:boolean}={}):Promise<WorkSessionDetail>{const response=await sandboxClient.getSandbox({sandboxId:id});if(!response.sandbox)throw new Error('工作会话不存在');return{...sessionFromSandbox(response.sandbox),proxyPath:response.sandbox.proxyPath,notebookUrl:response.sandbox.notebookUrl}}
export async function getWorkSessionProxy(id:string){const value=await getWorkSession(id);return{proxyPath:value.proxyPath,notebookUrl:value.notebookUrl}}
export async function getWorkSessionStatus(id:string):Promise<WorkSession>{return getWorkSession(id)}
export async function stopWorkSession(id:string):Promise<WorkSession>{const response=await sandboxClient.stopSandbox({sandboxId:id});if(!response.sandbox)throw new Error('停止会话失败');return sessionFromSandbox(response.sandbox)}
export async function resumeWorkSession(id:string):Promise<WorkSession>{const response=await sandboxClient.resumeSandbox({sandboxId:id});if(!response.sandbox)throw new Error('恢复会话失败');return sessionFromSandbox(response.sandbox)}

export async function listWorkSessionCells(id:string):Promise<WorkSessionCell[]>{const run=await latestRunForSandbox(id);if(!run){const response=await sandboxClient.listSandboxHistory({sandboxId:id});return response.cells.map((item)=>({id:item.id,source:item.source,output:item.output||[item.stdout,item.stderr].filter(Boolean).join('\n'),type:legacyCellType(item.type),exitCode:item.exitCode,success:item.success,createdAt:timestampString(item.createdAt),agent:item.agent,agentSessionId:item.agentThreadId,stopReason:item.stopReason||'旧会话历史',running:item.running}))}let token='';const cells:WorkSessionCell[]=[];let historyAvailable=false;do{const response=await runClient.listRunEvents({runId:run.runId,limit:500,pageToken:token});historyAvailable ||= response.historyAvailable;for(const item of response.events){if(item.kind!==RunEventKind.USER_MESSAGE&&item.kind!==RunEventKind.AGENT_MESSAGE)continue;cells.push({id:item.id,source:item.kind===RunEventKind.USER_MESSAGE?item.text:'',output:item.kind===RunEventKind.AGENT_MESSAGE?item.text:'',type:CellType.AGENT,exitCode:item.exitCode,success:item.success,createdAt:timestampString(item.createdAt),agent:item.agent,agentSessionId:'',stopReason:item.stopReason,running:false})}token=response.nextPageToken}while(token);if(!historyAvailable){let logs='';for await(const chunk of runClient.followRunLogs({runId:run.runId,projectId:run.projectId,follow:false,tailLines:1000})){logs+=chunk.data}if(logs)cells.push({id:`${run.runId}-legacy-log`,source:'',output:logs,type:CellType.AGENT,exitCode:0,success:true,createdAt:run.createdAt,agent:run.agentName,agentSessionId:'',stopReason:'旧运行：仅日志记录',running:false})}return cells}
export async function listWorkSessionEvents(id:string):Promise<WorkSessionEvent[]>{const run=await latestRunForSandbox(id);if(!run){const response=await sandboxClient.listSandboxHistory({sandboxId:id});return response.events.map((item)=>({id:item.id,type:item.type,level:item.level,message:item.message,createdAt:timestampString(item.createdAt)}))}const response=await runClient.listRunEvents({runId:run.runId,limit:500});return response.events.filter((v)=>v.kind===RunEventKind.STATUS).map((v)=>({id:v.id,type:'run.status',level:v.success?'info':'error',message:v.stopReason||v.payloadJson,createdAt:timestampString(v.createdAt)}))}
export async function getWorkSessionRunTarget(id:string):Promise<WorkSessionRunTarget|undefined>{const run=await latestRunForSandbox(id);return run?{projectId:run.projectId,agentName:run.agentName}:undefined}
export async function sendWorkSessionMessage(id:string,agent:string,message:string):Promise<void>{await sendWorkSessionMessageStream(id,agent,message,()=>{})}
export async function sendWorkSessionMessageStream(id:string,_agent:string,message:string,onEvent:(event:{type:'started'|'chunk'|'completed';runId:string;chunk?:string;isStderr?:boolean;run?:{id:string;agent:string;message:string;output:string;exitCode:number;success:boolean;createdAt:string;agentSessionId:string;stopReason:string;running:boolean}})=>void,signal?:AbortSignal,target?:WorkSessionRunTarget):Promise<void>{const previous=await latestRunForSandbox(id);const resolved=previous?{projectId:previous.projectId,agentName:previous.agentName}:target;if(!resolved)throw new Error('旧工作会话没有可用的 v2 项目和智能体，只能查看历史；请从智能体页面发起新运行');for await(const event of runClient.runAgentStream({projectId:resolved.projectId,agentName:resolved.agentName,prompt:message,source:RunSource.MANUAL,sandboxId:id},{signal})){if(event.eventType===RunAgentStreamEventType.STARTED)onEvent({type:'started',runId:event.runId});else if(event.eventType===RunAgentStreamEventType.OUTPUT)onEvent({type:'chunk',runId:event.runId,chunk:event.chunk,isStderr:event.stream===2});else if(event.eventType===RunAgentStreamEventType.COMPLETED){const run=event.run;onEvent({type:'completed',runId:event.runId,run:run?{id:run.runId,agent:run.agentName,message,output:'',exitCode:run.exitCode,success:run.status===3,createdAt:run.createdAt,agentSessionId:'',stopReason:run.error,running:false}:undefined})}}}
export async function watchWorkSession(id:string,onEvent:(event:WorkSessionWatchEvent)=>void,signal?:AbortSignal):Promise<void>{let previous='';while(!signal?.aborted){const session=await getWorkSessionStatus(id);const key=`${session.status}:${session.updatedAt}`;if(key!==previous){onEvent({type:'session',session});previous=key}await new Promise<void>((resolve)=>setTimeout(resolve,2000))}}

async function latestRunForSandbox(id:string){const response=await runClient.listRuns({sandboxId:id,limit:1});return response.runs[0]}
function legacyCellType(value:string):CellType{switch(value.trim().toLowerCase()){case'shell':return CellType.SHELL;case'javascript':return CellType.JAVASCRIPT;case'python':return CellType.PYTHON;default:return CellType.AGENT}}
function sessionFromSandbox(item:Sandbox):WorkSession{return{id:item.sandboxId,title:item.title,status:item.status,driver:item.driver,guestImage:item.image,workspacePath:item.workspacePath,triggerSource:item.triggerSource,createdAt:timestampString(item.createdAt),updatedAt:timestampString(item.updatedAt),cellCount:item.cellCount,eventCount:item.eventCount,tags:item.tags.map((v)=>({name:v.name,value:v.value}))}}
function timestampString(value?:{seconds:bigint;nanos:number}){return value?new Date(Number(value.seconds)*1000+value.nanos/1e6).toISOString():''}
