import { expect, test } from 'bun:test'; import { readFileSync } from 'node:fs';
test('builds an authoritative Agent sandbox inventory and gates live v2 actions by lifecycle', () => {
  const source = readFileSync(new URL('./SandboxListView.svelte', import.meta.url),'utf8');
  expect(source).toContain('Sandbox 清单');
  expect(source).toContain('listAllSandboxes');
  expect(source).toContain('sandboxService.listSandboxes');
  expect(source).toContain('filterSandboxes');
  expect(source).toContain('sandboxLifecycle(item.status)');
  expect(source).toContain('getSandboxStats');
  expect(source).toContain('execService.exec');
  expect(source).toContain('removeSandbox');
  expect(source).toContain('sandboxService.resumeSandbox');
  expect(source).toContain('sandboxService.stopSandbox');
  expect(source).not.toContain('runService.startRun');
  expect(source).not.toContain('buildSandboxResumeRequest');
  expect(source).not.toContain('buildSandboxStopRequest');
  expect(source).toContain('sandboxJupyterPath');
  expect(source).toContain('>恢复<');
  expect(source).toContain("'停止中' : '停止'");
  expect(source).toContain('>Jupyter<');
  expect(source).not.toContain("V2_CAPABILITIES['session-lifecycle']");
  expect(source).not.toContain('v2 未提供 Session 列表、停止、恢复、文件或 Jupyter 代理服务');
  expect(source).toContain("state === 'running'");
  expect(source).toContain("state === 'stopped'");
  expect(source).toContain("state === 'destroyed'");
  expect(source).toContain('{item.workspacePath ||');
  expect(source).toContain('{item.cellCount} cells');
  expect(source).not.toContain('runService.listRuns');
  expect(source).toContain('SessionTerminal');
  expect(source).toContain('FileBrowser');
  expect(source).toContain("openTool('terminal', item.sandboxId)");
  expect(source).toContain("openTool('files', item.sandboxId)");
  expect(source).toContain('sandboxId=${encodeURIComponent(sandboxId)}');
  expect(source).not.toMatch(/navigateTo\(['\"]session/);
});
